#cloud-config
package-upgrade: true
packages:
  - nginx
  - certbot
  - gnupg 
  # picking version does not seem to work, using snap in runcmd
  #- [nodejs, 20.10.0]
  #- [npm, 10.2.3]
write_files:
  - owner: www-data:www-data
    path: /etc/nginx/sites-available/default
    content: |
      server {
        listen 80;
        location / {
          proxy_pass http://127.0.0.1:3000;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection keep-alive;
          proxy_set_header Host $host;
          proxy_cache_bypass $http_upgrade;
        }
      }
runcmd:
  # install mongodb
  - echo "INSTALLING MONGODB"
  - curl -fsSL https://pgp.mongodb.com/server-7.0.asc | sudo gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor
  - echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
  - apt-get update
  - apt-get install -y mongodb-org
  - systemctl daemon-reload
  - systemctl enable mongod
  - systemctl start mongod
  - echo "INSTALLED MONGODB"
  # only leave ssh, http/s open
  - ufw default deny
  - ufw allow 'OpenSSH'
  - ufw allow 'Nginx Full'
  - ufw enable
  # mongodb with snap
  #- snap install mongo22 
  # node with snap as correct version not available with packages
  - snap install node --classic
  # install pm2 for daemonizing the node app
  - npm install pm2 -g
  # clone app from github
  - su -c 'cd ~ && git clone https://github.com/strokovnjaka/shroomate' - ubuntu
  # install dependencies
  - su -c 'cd ~/shroomate && npm install --legacy-peer-deps' - ubuntu
  # initialize db
  - su -c 'cd ~/shroomate && npm run init:db-local' - ubuntu
  # write the required .env file
  - |
    su -c 'cd ~/shroomate && echo "
    # environment
    NODE_ENV=production
    # JWT secret
    JWT_SECRET=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 32)
    # MongoDB access
    MONGODB_ATLAS_URI=\"mongodb://127.0.0.1:27017/shroomate?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.1.1\"" > .env' - ubuntu
  # start the app, prepare it to daemonize
  - su -c 'cd ~/shroomate && pm2 start app.js && pm2 save && pm2 startup systemd' - ubuntu
  # daemonize the app
  - env PATH=$PATH:/snap/node/8007/bin /usr/local/lib/node_modules/pm2/bin/pm2 startup systemd -u ubuntu --hp /home/ubuntu
